jobs:
  build:
    name: test mojap dependencies
    runs-on: ubuntu-latest
    strategy:
        fail-fast: true
        matrix:
          python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: check changes for conflicts with other mojap package dependencies
        uses: moj-analytical-services/actions-mojap-package-depends@main
        with:
          org-repo: ${{ github.event.repository.name }}
          repo: ${{ github.repository }}
